### ISSUE TITLE
with respect to term "human"

### ISSUE THREAD

**Issue by wrought** [sudoroom/sudo-humans#1]
http://io9.com/5962243/think-twice-before-using-mankind-to-mean-all-humanity-say-scholars

options to change it to, if desired:
- persons
- people
- sudoers
- "ers"

**Comment by rcsheets** [comment]
The referenced article seems to object to "man" and "mankind" as non-gender-neutral. I think "human" seems perfectly fine. If you disagree, I would ask that you reference some specific passage from the article, in case there's something I missed.

**Comment by yardenac** [comment]
humyns

**Comment by buzzaz** [comment]
keeping it serious though, I agree with RCS: We have to find a gender neutral term.
Persons is fine. Sudoers could work, but that's only if there are objections with persons. Right?

**Comment by yardenac** [comment]
I'm serious...

**Comment by buzzaz** [comment]
Okay, then in the interest of maintaining an engaged process, I'll address your suggestion:

There's nothing wrong with the term "Persons", maybe because every human being is a person. If there's a reason we cannot consider (or use) Persons, I (for one) would love to know.

Humyns seems to me\* to carry a connotation of the other term it sounds like: Womyn.
I'll let others say what that means: http://www.urbandictionary.com/define.php?term=womyn
- This is a term used by feminists who feel that having the word "man" in the word "woman" makes women a subset of men. So, to make themselves a non subset, they changed the letter 'e' to a 'y'.
- the feminist/lesbian spelling of "woman". also has political implications. not all feminists/lesbians use or even like this term, but it's been claimed as a subtle empowerment thing by both groups in general.
- I am a dedicated volunteer and a professional technical writer / product manager. I say that to signify that my work involves micro (or one-on-one,) scaled (as in startup,) and marco (or enterprise,) communication.

**Comment by rcsheets** [comment]
Human already seems gender-neutral to me. I agree with closing this issue, but if someone believes further discussion is warranted I'd like there to be a specific explanation of why "human" is problematic.
